#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#Python Template for ES2B4 Assignment

#Name: Pablo Navajas Helguero
#ID : 1604648
#Assignment: assignment_a1_2
#Section: A1_2

### Code for exercise 1:

from math import sin, cos, radians

Tangents = [(sin(radians(x))/cos(radians(x))) for x in range(0,90,1)]

print(Tangents)

### Code for exercise 2:

String = input('ENTER YOUR STRING: ')

VowelList = ['a','e','i','o','u','A','E','I','O','U']

Vowels = [a for a in String if a in VowelList]

print(Vowels)
print('')

### Code for exercise 3:

Solutions = tuple([(x, y) for x in range(-5,6) for y in range(0,11) if y == ((x**2)+5)])

print(Solutions)
