#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#Python Template for ES2B4 Assignment

#Name: Pablo Navajas Helguero
#ID : 1604648
#Assignment: assignment2_a1_1c1.py 
#Section: A1_1C1

### Your code below:

#Import the string library to create list of Punctuation
import string

#Set Word to false to create an infinite loop
Word = False
#Create loop
while Word == False:
        #Ask user to introduce a word
        Word = input('ENTER YOUR WORD: ')
        #Establsih the exit condition
        if Word == 'exit':
            print('Exiting from the program!')
            break
        
        #Divide the word so as to work with each letter
        Wordlist = list(Word)
        #Create the list of punctuation signs
        PUNCTUATION = string.punctuation
        #Create the list of vowels
        VOWELS = ['a', 'e', 'i', 'o', 'u','A','E','I','O','U']
        #Separate letters from punctuation signs to work independently with each list
        Wordlett = [x for x in Wordlist if x not in PUNCTUATION]
        WordPunc = [x for x in Wordlist if x in PUNCTUATION]
        #Save the initial letter to check if it starts with a vowel or a consonant
        a = Wordlett[0]
        
        #Check if the word starts by a Vowel
        if a in VOWELS:
            #If so add the punctuation signs and then 'hay'
            NewWord = Wordlett + WordPunc
            NewWord.append('hay')
            
        #If it does not start by vowel
        else:
            #Move the initial letter to the end of the word
            Wordlett.remove(a)
            Wordlett.append(a)
            #Add the punctuation signs and then 'ay'
            NewWord = Wordlett + WordPunc
            NewWord.append('ay')
            
        #Join the elements of the final list and print them as the final word
        strNewWord = ''.join(str(e) for e in NewWord)
        print('Your word converted to Pig-Latin is: ', strNewWord)
        #Restart the loop
        Word = False
